/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: "#1455ce",
        "primary-container": "#3b6fe8",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b3c5ff",
        "inverse-primary": "#b3c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#001849",
        "on-primary-fixed-variant": "#003fa4",
        "surface-tint": "#1656cf",
        secondary: "#b31a62",
        "secondary-container": "#fd599a",
        "secondary-fixed": "#ffd9e2",
        "secondary-fixed-dim": "#ffb1c8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#610031",
        "on-secondary-fixed": "#3e001d",
        "on-secondary-fixed-variant": "#8e004a",
        tertiary: "#825400",
        "tertiary-container": "#a36a00",
        "tertiary-fixed": "#ffddb4",
        "tertiary-fixed-dim": "#ffb955",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#633f00",
        surface: "#f9f9f7",
        "surface-dim": "#dadad8",
        "surface-bright": "#f9f9f7",
        "surface-variant": "#e2e3e1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f2",
        "surface-container": "#eeeeec",
        "surface-container-high": "#e8e8e6",
        "surface-container-highest": "#e2e3e1",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#434654",
        "on-background": "#1a1c1b",
        background: "#f9f9f7",
        outline: "#737685",
        "outline-variant": "#c3c6d6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'Inter', 'sans-serif'],
        body: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        label: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        premium: '0 2px 12px rgba(0,0,0,0.04)',
        'premium-hover': '0 4px 20px rgba(0,0,0,0.06)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem', // Match "ROUND_EIGHT" or 16px as described in Stitch designMd
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
